### ISSUE TITLE
ImportError: cannot import name 'iou3d_nms_cuda' from 'pcdet.ops.iou3d_nms' (unknown location)

### ISSUE THREAD

**Issue by Mahmood-Hussain** [tianweiy/CenterPoint-KITTI#10]
While running 
`python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml
`

I get this strange error. I could not found anything related on internet

Traceback (most recent call last):
  File "/home/mahmood/anaconda3/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/mahmood/anaconda3/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/media/storage2/CenterPoint-KITTI/pcdet/datasets/__init__.py", line 7, in <module>
    from .dataset import DatasetTemplate
  File "/media/storage2/CenterPoint-KITTI/pcdet/datasets/dataset.py", line 8, in <module>
    from .augmentor.data_augmentor import DataAugmentor
  File "/media/storage2/CenterPoint-KITTI/pcdet/datasets/augmentor/data_augmentor.py", line 6, in <module>
    from . import augmentor_utils, database_sampler
  File "/media/storage2/CenterPoint-KITTI/pcdet/datasets/augmentor/database_sampler.py", line 5, in <module>
    from ...ops.iou3d_nms import iou3d_nms_utils
  File "/media/storage2/CenterPoint-KITTI/pcdet/ops/iou3d_nms/iou3d_nms_utils.py", line 9, in <module>
    from . import iou3d_nms_cuda
ImportError: cannot import name 'iou3d_nms_cuda' from 'pcdet.ops.iou3d_nms' (unknown location)

**Comment by tianweiy** [comment]
you need to build the iou_nms first. see https://github.com/tianweiy/CenterPoint-KITTI/blob/main/docs/INSTALL.md

**Comment by Mahmood-Hussain** [comment]
Processing ./spconv-1.2.1-cp38-cp38-linux_x86_64.whl
Installing collected packages: spconv
Successfully installed spconv-1.2.1


Using /home/mahmood/anaconda3/lib/python3.8/site-packages
Searching for typing-extensions==3.7.4.3
Best match: typing-extensions 3.7.4.3
Adding typing-extensions 3.7.4.3 to easy-install.pth file

Using /home/mahmood/anaconda3/lib/python3.8/site-packages
Finished processing dependencies for pcdet==0.3.0+ef36fce



THANK YOU FOR YOUR REPLY. ACTUALLY THE ORDER OF INSTRUCTIONS YOU MENTIONED IN INSTALLATION.MD IS NECESSARY. I followed the order and it worked!
