### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by Mahmood-Hussain** [tianweiy/CenterPoint-KITTI#11]
Hello, I am getting this error anybody having information about this?

epochs:   0%|                                                                                                                   | 0/80 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main()
  File "train.py", line 170, in main
    merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
  File "/media/storage1/CenterPoint-KITTI/tools/train_utils/train_utils.py", line 93, in train_model
    dataloader_iter=dataloader_iter
  File "/media/storage1/CenterPoint-KITTI/tools/train_utils/train_utils.py", line 38, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/media/storage1/CenterPoint-KITTI/pcdet/models/__init__.py", line 30, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/mahmood/anaconda3/envs/openpcdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/storage1/CenterPoint-KITTI/pcdet/models/detectors/centerpoint.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/mahmood/anaconda3/envs/openpcdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/storage1/CenterPoint-KITTI/pcdet/models/dense_heads/centerpoint_head_single.py", line 78, in forward
    gt_boxes=data_dict['gt_boxes']
  File "/media/storage1/CenterPoint-KITTI/pcdet/models/dense_heads/centerpoint_head_single.py", line 142, in assign_targets
    heatmaps = np.array(heatmaps).transpose(1, 0).tolist()
  File "/home/mahmood/anaconda3/envs/openpcdet/lib/python3.7/site-packages/torch/_tensor.py", line 643, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by tianweiy** [comment]
see https://github.com/tianweiy/CenterPoint-KITTI/issues/5

**Comment by Mahmood-Hussain** [comment]
Yes, It solved my problem
Thank You so much
