### ISSUE TITLE
ImportError: cannot import name 'iou3d_nms_cuda' from 'pcdet.ops.iou3d_nms' (unknown location)

### ISSUE THREAD

**Issue by bhargav-inthezone** [tianweiy/CenterPoint-KITTI#12]
When I ran python /content/CenterPoint-KITTI-main/tools/train.py --cfg_file ${CONFIG_FILE} , I'm getting this error

Traceback (most recent call last):
  File "/content/CenterPoint-KITTI-main/tools/train.py", line 11, in <module>
    from test import repeat_eval_ckpt
  File "/content/CenterPoint-KITTI-main/tools/test.py", line 13, in <module>
    from eval_utils import eval_utils
  File "/content/CenterPoint-KITTI-main/tools/eval_utils/eval_utils.py", line 7, in <module>
    from pcdet.models import load_data_to_gpu
  File "/content/CenterPoint-KITTI-main/pcdet/models/__init__.py", line 6, in <module>
    from .detectors import build_detector
  File "/content/CenterPoint-KITTI-main/pcdet/models/detectors/__init__.py", line 1, in <module>
    from .detector3d_template import Detector3DTemplate
  File "/content/CenterPoint-KITTI-main/pcdet/models/detectors/detector3d_template.py", line 6, in <module>
    from ...ops.iou3d_nms import iou3d_nms_utils
  File "/content/CenterPoint-KITTI-main/pcdet/ops/iou3d_nms/iou3d_nms_utils.py", line 9, in <module>
    from . import iou3d_nms_cuda
ImportError: cannot import name 'iou3d_nms_cuda' from 'pcdet.ops.iou3d_nms' (unknown location)
[22]

**Comment by tianweiy** [comment]
see https://github.com/tianweiy/CenterPoint-KITTI/issues/10
