### ISSUE TITLE
   raise FileNotFoundError : File "/content/CenterPoint-KITTI-main/OpenPCDet/pcdet/models/detectors/detector3d_template.py", line 350, in load_params_with_optimizer  

### ISSUE THREAD

**Issue by bhargav-inthezone** [tianweiy/CenterPoint-KITTI#14]
I am using GPU in colab, I have set --ckpt argument to 0 
When I ran train.py --cfg_file centerpoint.yaml I am getting this error.

Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main()
  File "train.py", line 129, in main
    it, start_epoch = model.load_params_with_optimizer(args.ckpt, to_cpu=dist, optimizer=optimizer, logger=logger)
  File "/content/CenterPoint-KITTI-main/OpenPCDet/pcdet/models/detectors/detector3d_template.py", line 350, in load_params_with_optimizer
    raise FileNotFoundError
FileNotFoundError

**Comment by bhargav-inthezone** [comment]
i gave an invalid argument
