### ISSUE TITLE
Running the NN on Colab

### ISSUE THREAD

**Issue by koraykoca** [tianweiy/CenterPoint-KITTI#31]
Hi there,

we are interested in your work and trying to implement it for a lecture at the university. Since we don't have a laptop with GPU, we want to run it on Colab. We went through the installation and demo instructions. We have been struggling with a lot of compatibility issues and we could not run the network. Below you can see our approach on Colab:

1. we cloned OpenPCDet, install requirements.
2. we install vtk==8.1.2 and mayavi. 
3. we installed cmake==3.13.0
4. we installed spconv v 1.2.1 with 
!pip install git+https://github.com/traveller59/spconv.git@v1.2.1 
5. Colab comes with 1.9.0+cu111. we uninstalled this and installed 1.3.0+cu100
6. we run python setup.py develop
7. We added a pre-trained model (checkpoint_epoch_80.pth) from your repo and one frame from KITTI to Colab
8. we run this command
!python /content/OpenPCDet/tools/demo.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml \
    --ckpt checkpoint_epoch_80.pth \
    --data_path /content/OpenPCDet/tools/000000.bin

We have these errors after step 8:

/usr/local/lib/python3.7/dist-packages/traits/etsconfig/etsconfig.py:412: UserWarning: Environment variable "HOME" not set, setting home directory to /tmp
  % (environment_variable, parent_directory)
Traceback (most recent call last):
  File "/content/OpenPCDet/tools/demo.py", line 10, in <module>
    from pcdet.datasets import DatasetTemplate
  File "/content/OpenPCDet/pcdet/datasets/__init__.py", line 7, in <module>
    from .dataset import DatasetTemplate
  File "/content/OpenPCDet/pcdet/datasets/dataset.py", line 8, in <module>
    from .augmentor.data_augmentor import DataAugmentor
  File "/content/OpenPCDet/pcdet/datasets/augmentor/data_augmentor.py", line 6, in <module>
    from . import augmentor_utils, database_sampler
  File "/content/OpenPCDet/pcdet/datasets/augmentor/database_sampler.py", line 5, in <module>
    from ...ops.iou3d_nms import iou3d_nms_utils
  File "/content/OpenPCDet/pcdet/ops/iou3d_nms/iou3d_nms_utils.py", line 9, in <module>
    from . import iou3d_nms_cuda
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

We are stuck here and have been dealing with this for many days. What is the problem? How should we implement this network on Colab? Could you help us?

**Comment by koraykoca** [comment]
I solved it using Google Cloud Deep Learning VM.
