### ISSUE TITLE
help，KeyError: 'CenterPoint'

### ISSUE THREAD

**Issue by MLbeginner2** [tianweiy/CenterPoint-KITTI#32]
the error in running train.py 
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main()
  File "train.py", line 115, in main
    model = build_network(model_cfg=cfg.MODEL, num_class=len(cfg.CLASS_NAMES), dataset=train_set)
  File "/data/DL/3D_Detect/OpenPCDet-master/pcdet/models/__init__.py", line 18, in build_network
    model_cfg=model_cfg, num_class=num_class, dataset=dataset
  File "/data/DL/3D_Detect/OpenPCDet-master/pcdet/models/detectors/__init__.py", line 25, in build_detector
    model = __all__[model_cfg.NAME](
KeyError: 'CenterPoint'

**Comment by koraykoca** [comment]
hi, I wonder if you get the correct results in the demo section? For example, I want to demo 000008.bin from the KITTI dataset but it looks like the pre-trained model shared here doesn't work well and assigns boxes randomly. How is it for you? 

I run this command for it: 
python demo.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ~/OpenPCDet/tools/checkpoint_epoch_80.pth --data_path ~/OpenPCDet/data/kitti/training/velodyne/000008.bin

The image from demo: 
<img width="767" alt="f" src="https://user-images.githubusercontent.com/20690194/142774289-d496e6bb-6aa0-4498-bed6-7ad0316c9100.png">

**Comment by tianweiy** [comment]
@MLbeginner2  your are using the original openpcdet (see the path) so it won't get centerpoint 

@koraykoca which model are you using? The model at https://github.com/tianweiy/CenterPoint-KITTI/issues/9 is not for pvrcnn

**Comment by koraykoca** [comment]
@tianweiy I am using the model from #9 (checkpoint_epoch_80.pth) because I couldn't find any other pre-trained model for KITTI.  What should I use?

**Comment by tianweiy** [comment]
you can use this model with this specific config https://github.com/tianweiy/CenterPoint-KITTI/blob/main/tools/cfgs/kitti_models/centerpoint.yaml

**Comment by koraykoca** [comment]
@tianweiy Thank you for your answer. When I run the demo with that centerpoint.yaml config, I get the same error:

Traceback (most recent call last):
  File "demo.py", line 104, in <module>
    main()
  File "demo.py", line 82, in main
    model = build_network(model_cfg=cfg.MODEL, num_class=len(cfg.CLASS_NAMES), dataset=demo_dataset)
  File "/home/koraykoca34/OpenPCDet/pcdet/models/__init__.py", line 18, in build_network
    model_cfg=model_cfg, num_class=num_class, dataset=dataset
  File "/home/koraykoca34/OpenPCDet/pcdet/models/detectors/__init__.py", line 25, in build_detector
    model = __all__[model_cfg.NAME](
KeyError: 'CenterPoint'

My command is: ~/OpenPCDet/tools$ python demo.py --cfg_file ~/CenterPoint-KITTI/tools/cfgs/kitti_models/centerpoint.yaml --ckpt checkpoint_epoch_80.pth --data_path ~/OpenPCDet/data/kitti/training/velodyne/000008.bin

**Comment by tianweiy** [comment]
similar to issue above, you are now using openpcdet repo instead of the current repo so you will get the keyerror. If you want to use openpcdet, you can you config and models at https://github.com/open-mmlab/OpenPCDet

**Comment by tianweiy** [comment]
I just update the docs, please clone centerpoint-kitti instead of the original openpcdet 

git clone https://github.com/tianweiy/CenterPoint-KITTI.git

Best

**Comment by koraykoca** [comment]
@tianweiy now it is working thank you very much. For future users, you need to run the command python setup.py develop again after cloning the repo. 

I want to ask a follow-up question. For this scene (from KITTI - 000001): 
![000001](https://user-images.githubusercontent.com/20690194/142776356-98add387-e98b-43d7-bd9e-45168db0949e.png)

I got this demo result:
<img width="682" alt="Screenshot_5" src="https://user-images.githubusercontent.com/20690194/142776384-d5bd45c7-2669-478f-b2db-a05d5a8148f4.png">

However, I didn't understand if it works as intended. For example, what are all those boxes on the left side of the demo output? On the scene, there is mostly empty and there are just trees.

**Comment by tianweiy** [comment]
there are probably false positive. you need to make this value higher for real inference https://github.com/tianweiy/CenterPoint-KITTI/blob/222232e5554cbe6e3d19d90faa8e1be4fd11fd3d/tools/cfgs/kitti_models/centerpoint.yaml#L52

currently the threshold maximizes ap which is not sensitive to false positive

**Comment by koraykoca** [comment]
okay, I tried it. As I increase that value, the number of FP decreases, but the bus ahead and the cyclist on the right are not detected. I want to work on your network and train it with the KITTI dataset. What would you suggest to me for the training or modifications of this network to make it perform better on the KITTI dataset? Does adding BiFPN layers make sense for example? Or should I focus on Data Augmentation techniques?
