### ISSUE TITLE
Kitti dataset preprocess without images

### ISSUE THREAD

**Issue by DJNing** [tianweiy/CenterPoint-KITTI#43]
Since this is a Lidar-only object detection model, could we preprocess the data without the images? I think if we don't use the evaluation metric of 'bbox', we can ignore the infos from images, right?

**Comment by tianweiy** [comment]
> Since this is a Lidar-only object detection model, could we preprocess the data without the images? I think if we don't use the evaluation metric of 'bbox', we can ignore the infos from images, right?

I think so ?

> Another question is, why do we only count the points inside the gt in the FOV of the image?
only these boxes are annotated

**Comment by tianweiy** [comment]
yeah, i think this should work

**Comment by jqfromsjtu** [comment]
Could you provide more details about how to ignore infos from image? I've got a dataset that only contains lidars's info and I arrange the files in KITTI's format and directories. I've made it work in the training process , but there's error in the evaluation process. I'm new to deep learning and python, but I'm gussing that something went wrong when accessing the evaluation data. Infos about cameras like alpha, truncation, occlusion, etc, are default to zero and xmin, ymin, xmax, ymax are default to a fixed but irrelevant value.

Error like these:
2022-03-17 12:22:55,146   INFO  *************** EPOCH 2 EVALUATION *****************
epochs:  50%|█████████████████▌                 | 1/2 [04:49<04:49, 289.23s/it, loss=2.76, lr=0.0028]
Traceback (most recent call last):                                           | 0/100 [00:00<?, ?it/s]
  File "train.py", line 223, in <module>
    main()
  File "train.py", line 187, in main
    merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
  File "/home/zzzz/CenterPoint-KITTI/tools/train_utils/train_utils.py", line 123, in train_model
    result_dir=result_dir
  File "/home/zzzz/CenterPoint-KITTI/tools/eval_utils/eval_utils.py", line 58, in eval_one_epoch
    pred_dicts, ret_dict = model(batch_dict)
  File "/home/zzzz/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zzzz/CenterPoint-KITTI/pcdet/models/detectors/pointpillar.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/zzzz/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zzzz/CenterPoint-KITTI/pcdet/models/backbones_2d/map_to_bev/pointpillar_scatter.py", line 18, in forward
    batch_size = coords[:, 0].max().int().item() + 1
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.
eval:   0%|                                                                  | 0/100 [00:01<?, ?it/s]

**Comment by francescofact** [comment]
> Thanks for the reply, I think I've made it work now. One more question, how to change the number of target classes for the network? Can I just change the CLASS_NAMES in the network YAML directly?

How did you managed to preprocess the kitti dataset without the calibration images? I also have a lidar only dataset
