### ISSUE TITLE
RuntimeError: Error compiling objects for extension 

### ISSUE THREAD

**Issue by up198** [tianweiy/CenterPoint-KITTI#46]
when I run the seyup.py there are some error and here is my conda environment.
can someone help me to solve these problem
=====================================================================

pcdet                     0.3.0+95b7309             dev_0    <develop>
pcre                      8.45                 h295c915_0  
pillow                    8.3.2                    pypi_0    pypi
pip                       21.2.2           py36h06a4308_0  
protobuf                  3.17.3                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pyface                    7.3.0            py36h06a4308_1  
pygments                  2.11.2             pyhd3eb1b0_0  
pyparsing                 2.4.7                    pypi_0    pypi
pyqt                      5.9.2            py36h05f1152_2  
python                    3.6.13               h12debd9_1  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.7.0           py3.6_cuda11.0.221_cudnn8.0.3_0    pyt

=====================================================================
log msg:

running develop
running egg_info
writing pcdet.egg-info/PKG-INFO
writing dependency_links to pcdet.egg-info/dependency_links.txt
writing requirements to pcdet.egg-info/requires.txt
writing top-level names to pcdet.egg-info/top_level.txt
reading manifest file 'pcdet.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'pcdet.egg-info/SOURCES.txt'
running build_ext
building 'pcdet.ops.iou3d_nms.iou3d_nms_cuda' extension
Emitting ninja build file /home/lidar/centerpoint_workspace/CenterPoint-KITTI/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /usr/local/cuda/bin/nvcc -I/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/include -I/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/include/TH -I/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/lidar/anaconda3/envs/centerpoint/include/python3.6m -c -c /home/lidar/centerpoint_workspace/CenterPoint-KITTI/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.cu -o /home/lidar/centerpoint_workspace/CenterPoint-KITTI/build/temp.linux-x86_64-3.6/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/lidar/centerpoint_workspace/CenterPoint-KITTI/build/temp.linux-x86_64-3.6/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o 
/usr/local/cuda/bin/nvcc -I/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/include -I/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/include/TH -I/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/lidar/anaconda3/envs/centerpoint/include/python3.6m -c -c /home/lidar/centerpoint_workspace/CenterPoint-KITTI/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.cu -o /home/lidar/centerpoint_workspace/CenterPoint-KITTI/build/temp.linux-x86_64-3.6/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_86'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1522, in _run_ninja_build
    env=env)
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 106, in <module>
    'src/sampling_gpu.cu',
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/lidar/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by Felix-fz** [comment]
Hi, do you have solved it? I have the same problem, but I do not konw the soultion.
