### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'ANCHOR_GENERATOR_CONFIG'

### ISSUE THREAD

**Issue by CCZU-Myan** [tianweiy/CenterPoint-KITTI#54]
I have a problem ,When i try centerpoint on openpcd 
python train.py --cfg_file=cfgs/kitti_models/centerpoint.yaml 

Traceback (most recent call last):
  File "train.py", line 230, in <module>
    main()
  File "train.py", line 129, in main
    model = build_network(model_cfg=cfg.MODEL, num_class=len(cfg.CLASS_NAMES), dataset=train_set)
  File "/home/yb/OpenPCDet/tools/../pcdet/models/__init__.py", line 17, in build_network
    model = build_detector(
  File "/home/yb/OpenPCDet/tools/../pcdet/models/detectors/__init__.py", line 42, in build_detector
    model = __all__[model_cfg.NAME](
  File "/home/yb/OpenPCDet/tools/../pcdet/models/detectors/centerpoint.py", line 7, in __init__
    self.module_list = self.build_networks()
  File "/home/yb/OpenPCDet/tools/../pcdet/models/detectors/detector3d_template.py", line 46, in build_networks
    module, model_info_dict = getattr(self, 'build_%s' % module_name)(
  File "/home/yb/OpenPCDet/tools/../pcdet/models/detectors/detector3d_template.py", line 128, in build_dense_head
    dense_head_module = dense_heads.__all__[self.model_cfg.DENSE_HEAD.NAME](
  File "/home/yb/OpenPCDet/tools/../pcdet/models/dense_heads/anchor_head_single.py", line 10, in __init__
    super().__init__(
  File "/home/yb/OpenPCDet/tools/../pcdet/models/dense_heads/anchor_head_template.py", line 26, in __init__
    anchor_generator_cfg = self.model_cfg.ANCHOR_GENERATOR_CONFIG
AttributeError: 'EasyDict' object has no attribute 'ANCHOR_GENERATOR_CONFIG'
how to do?

**Comment by CCZU-Myan** [comment]
> 我有一个问题，当我在 openpcd python train.py上尝试 centerpoint 时--cfg_file=cfgs/kitti_models/centerpoint.yaml
> 
> 回溯（最近一次调用最后一次）： 文件“train.py”，第 230 行，在 main() 文件“train.py”，第 129 行，在主 模型 = build_network(model_cfg=cfg.MODEL, num_class=len(cfg. CLASS_NAMES), dataset=train_set) 文件 "/home/yb/OpenPCDet/tools/../pcdet/models/ **init** .py"，第 17 行，在 build_network model = build_ detector( 文件 "/home/yb/OpenPCDet/tools/ ../pcdet/models/ detectors **/ init** .py"，第 42 行，在 build_ detector model = **all** [model_cfg.NAME]( File "/home/yb/OpenPCDet/tools/../pcdet/models/ detectors/centerpoint. py”，第 7 行，在**init** self.module_list = self.build_networks() 文件“/home/yb/OpenPCDet/tools/../pcdet/models/ detectors/ detector3d_template.py”，第 46 行，在 build_networks 模块中，model_info_dict = getattr(self, 'build_%s' % module_name)( File "/home/yb/OpenPCDet/tools/../pcdet/models/ detectors/ detector3d_template.py", 第 128 行，在 build_dense_head dendense_head_module = **dend_heads.all** [ self.model_cfg.DENSE_HEAD.NAME]( 文件 "/home/yb/OpenPCDet/tools/../pcdet/models/dense_heads/anchor_head_single.py"，第 10 行，**init** super() 中。**init** ( 文件 "/home/yb/OpenPCDet/tools/../pcdet/models/dense_heads/anchor_head_template.py"，第 26 行，在**initanchor_generator_cfg** = self.model_cfg.ANCHOR_GENERATOR_CONFIG AttributeError: 'EasyDict' 对象没有属性 'ANCHOR_GENERATOR_CONFIG ' 怎么做？

@tianweiy
